name: Fetch Jobs

on:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Call Fetch Endpoint
        run: |
           curl https://placement-tracker-38tw.onrender.com/fetch-jobs