name: NORS Scheduler

on:
  schedule:

    - cron: "0 */6 * * *"

  workflow_dispatch:

jobs:

  run:

    runs-on: ubuntu-latest

    steps:

      - name: Wake NORS

        run: |
          curl https://placement-tracker-38tw.onrender.com/fetch-jobs

      - name:Send Mail 

        run: |
          curl https://placement-tracker-38tw.onrender.com/send-alerts

      - name:Cleanup Jobs

        run: |
          curl https://placement-tracker-38tw.onrender.com//cleanup-jobs