name: Send Emails

on:
  schedule:
    - cron: '0 8 * * *'

jobs:
  email:
    runs-on: ubuntu-latest

    steps:
      - name: Send Emails
      
        run: |
          curl https://placement-tracker-38tw.onrender.com/send-alerts

      